version: '3'
services:
  server:
    image: clojure:lein-alpine
    hostname: kitsune-api
    working_dir: /root
    command: lein repl :headless :host 0.0.0.0 :port 38001
    ports:
      - 3000:3000
      - 38001:38001
    volumes:
      - .:/root
    depends_on:
      - docker_db
    networks:
      default:
        aliases:
          - kitsune.devel

  docker_db:
    image: postgres:alpine
    volumes:
      - ./psql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kitsune
      POSTGRES_DB: kitsune
      POSTGRES_PASSWORD: whatever
    ports:
      - 5432

  adminer:
    image: adminer
    ports:
      - 8080:8080
